name: release

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: release from actions
      run: |
        echo "release from actions"
      shell: bash
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # v4.2.0
      with:
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ input.GITHUB_TOKEN }}

